// ── MCP Provider Registry ─────────────────────────────────────────────────────

export interface McpProvider {
  slug: string;
  name: string;
  category: "database" | "automation" | "devtools" | "communication" | "payments" | "analytics" | "content" | "storage" | "design";
  icon: string;
  description: string;
  /**
   * Static URL, dynamic function from creds, or null for REST-only providers.
   * For authType "mcp_url" the full URL (with embedded token) comes from creds —
   * set mcpServerUrl to a function that reads it, e.g. (c) => c.make_mcp_url.
   */
  mcpServerUrl: string | null | ((creds: Record<string, string>) => string);
  /**
   * How the credential is passed:
   *  bearer_token — Authorization: Bearer {token} via Anthropic authorization_token
   *  api_key      — same as bearer_token, but may use a custom header (see authHeader)
   *  mcp_url      — full MCP URL including embedded token supplied by the user
   *  webhook_url  — prompt-only webhook trigger, no MCP
   *  rest_api     — prompt-only REST calls generated by Claude
   *  admin_api    — platform-specific admin API, prompt-only
   *  basic_auth   — HTTP Basic auth, prompt-only
   */
  authType: "bearer_token" | "api_key" | "mcp_url" | "webhook_url" | "rest_api" | "admin_api" | "basic_auth";
  /** Custom HTTP header name when the server doesn't use Authorization: Bearer. */
  authHeader?: string;
  credentialFields: Array<{
    key: string;
    label: string;
    type: "text" | "password" | "url";
    placeholder?: string;
    help?: string;
    optional?: boolean;
  }>;
  supportsRealMCP: boolean;
  /** System-prompt hint injected into REST-only action context. */
  restApiHint?: string;
  /**
   * Internal platform-level tools — loaded automatically from env vars,
   * not shown in the MCP store, not requiring user credentials.
   */
  internal?: boolean;
}

export const MCP_REGISTRY: Record<string, McpProvider> = {
  // ── Real MCP providers (supportsRealMCP: true) ────────────────────────────

  github: {
    slug: "github",
    name: "GitHub",
    category: "devtools",
    icon: "🐙",
    description: "Create repos, manage issues, open pull requests, and more via the GitHub MCP server",
    mcpServerUrl: "https://api.githubcopilot.com/mcp/",
    authType: "bearer_token",
    credentialFields: [
      {
        key: "github_token",
        label: "Personal Access Token",
        type: "password",
        placeholder: "ghp_...",
        help: "Create at github.com/settings/tokens — needs repo and workflow scopes",
      },
    ],
    supportsRealMCP: true,
  },

  stripe: {
    slug: "stripe",
    name: "Stripe",
    category: "payments",
    icon: "💳",
    description: "Manage payments, customers, subscriptions, and products via the Stripe MCP server",
    mcpServerUrl: "https://mcp.stripe.com",
    authType: "bearer_token",
    credentialFields: [
      {
        key: "stripe_key",
        label: "Stripe API Key",
        type: "password",
        placeholder: "sk_live_... or rk_live_...",
        help: "Use a Restricted Key from dashboard.stripe.com/apikeys for least privilege",
      },
    ],
    supportsRealMCP: true,
  },

  linear: {
    slug: "linear",
    name: "Linear",
    category: "devtools",
    icon: "📋",
    description: "Create and manage issues, projects, and cycles via the Linear MCP server",
    mcpServerUrl: "https://mcp.linear.app/sse",
    authType: "bearer_token",
    credentialFields: [
      {
        key: "linear_key",
        label: "Linear API Key",
        type: "password",
        placeholder: "lin_api_...",
        help: "Create at linear.app/settings/api under Personal API Keys",
      },
    ],
    supportsRealMCP: true,
  },

  vercel: {
    slug: "vercel",
    name: "Vercel",
    category: "devtools",
    icon: "▲",
    description: "Deploy projects, manage domains, and view deployments via the Vercel MCP server",
    mcpServerUrl: "https://mcp.vercel.com",
    authType: "bearer_token",
    credentialFields: [
      {
        key: "vercel_token",
        label: "Vercel Account Token",
        type: "password",
        placeholder: "...",
        help: "Create at vercel.com/account/tokens",
      },
    ],
    supportsRealMCP: true,
  },

  cloudflare: {
    slug: "cloudflare",
    name: "Cloudflare",
    category: "devtools",
    icon: "🌥️",
    description: "Manage Workers, KV, R2, and DNS records via the Cloudflare MCP server",
    mcpServerUrl: "https://mcp.cloudflare.com/sse",
    authType: "bearer_token",
    credentialFields: [
      {
        key: "cf_token",
        label: "Cloudflare API Token",
        type: "password",
        placeholder: "...",
        help: "Create at dash.cloudflare.com/profile/api-tokens",
      },
    ],
    supportsRealMCP: true,
  },

  sentry: {
    slug: "sentry",
    name: "Sentry",
    category: "devtools",
    icon: "🪲",
    description: "Query errors, manage issues, and view performance data via the Sentry MCP server",
    mcpServerUrl: "https://mcp.sentry.dev/mcp",
    authType: "bearer_token",
    credentialFields: [
      {
        key: "sentry_token",
        label: "Sentry Internal Integration Token",
        type: "password",
        placeholder: "...",
        help: "Create an Internal Integration at sentry.io/settings/ → Integrations",
      },
    ],
    supportsRealMCP: true,
  },

  notion: {
    slug: "notion",
    name: "Notion",
    category: "content",
    icon: "📝",
    description: "Read and write pages, databases, and blocks via the Notion MCP server",
    mcpServerUrl: "https://mcp.notion.com/mcp",
    authType: "bearer_token",
    credentialFields: [
      {
        key: "notion_token",
        label: "Notion Integration Token",
        type: "password",
        placeholder: "secret_...",
        help: "Create an integration at notion.com/profile/integrations and share pages with it",
      },
    ],
    supportsRealMCP: true,
  },

  n8n: {
    slug: "n8n",
    name: "n8n",
    category: "automation",
    icon: "⚙️",
    description: "Trigger and manage n8n workflows via your self-hosted n8n MCP endpoint",
    mcpServerUrl: (creds: Record<string, string>) =>
      `${(creds["instance_url"] ?? "").replace(/\/+$/, "")}/mcp`,
    authType: "bearer_token",
    credentialFields: [
      {
        key: "instance_url",
        label: "n8n Instance URL",
        type: "url",
        placeholder: "https://n8n.yourdomain.com",
        help: "The public URL of your n8n instance (must be accessible from the internet)",
      },
      {
        key: "api_key",
        label: "n8n API Key",
        type: "password",
        placeholder: "n8n_...",
        help: "Create at your n8n instance → Settings → API",
      },
    ],
    supportsRealMCP: true,
  },

  make: {
    slug: "make",
    name: "Make",
    category: "automation",
    icon: "🔧",
    description: "Run Make scenarios using your personal Make MCP endpoint",
    mcpServerUrl: (creds: Record<string, string>) => creds["make_mcp_url"] ?? "",
    authType: "mcp_url",
    credentialFields: [
      {
        key: "make_mcp_url",
        label: "Make MCP URL",
        type: "url",
        placeholder: "https://eu2.make.com/mcp/api/v1/u/YOUR_TOKEN/sse",
        help: "Go to Make.com → Profile → API → MCP → Copy your zone URL",
      },
    ],
    supportsRealMCP: true,
  },

  zapier: {
    slug: "zapier",
    name: "Zapier",
    category: "automation",
    icon: "⚡",
    description: "Trigger Zapier actions using your personal Zapier MCP endpoint",
    mcpServerUrl: (creds: Record<string, string>) => creds["zapier_mcp_url"] ?? "",
    authType: "mcp_url",
    credentialFields: [
      {
        key: "zapier_mcp_url",
        label: "Zapier MCP URL",
        type: "url",
        placeholder: "https://mcp.zapier.com/api/mcp/s/YOUR_TOKEN/mcp",
        help: "Go to zapier.com/mcp → Create MCP → Copy your unique URL",
      },
    ],
    supportsRealMCP: true,
  },

  figma: {
    slug: "figma",
    name: "Figma",
    category: "design",
    icon: "🎨",
    description: "Read Figma files, components, and design tokens via the Figma MCP server",
    mcpServerUrl: "https://mcp.figma.com/mcp",
    authType: "bearer_token",
    credentialFields: [
      {
        key: "figma_access_token",
        label: "Figma Personal Access Token",
        type: "password",
        placeholder: "figd_...",
        help: "Create at figma.com → Account → Personal Access Tokens",
      },
    ],
    supportsRealMCP: true,
  },

  "google-stitch": {
    slug: "google-stitch",
    name: "Google Stitch",
    category: "design",
    icon: "🧵",
    description: "Generate UI designs from prompts and extract production-ready code",
    mcpServerUrl: "https://stitch.googleapis.com/mcp",
    authType: "api_key",
    authHeader: "X-Goog-Api-Key",
    credentialFields: [
      {
        key: "stitch_api_key",
        label: "Google Stitch API Key",
        type: "password",
        placeholder: "AIza...",
        help: "console.cloud.google.com → APIs → Enable Stitch API → Credentials → Create API Key",
      },
    ],
    supportsRealMCP: true,
  },

  // ── REST / credential-only providers (supportsRealMCP: false) ─────────────

  shopify: {
    slug: "shopify",
    name: "Shopify",
    category: "content",
    icon: "🛍️",
    description: "Manage Shopify store products, orders, and customers via the Admin GraphQL API",
    mcpServerUrl: null,
    authType: "admin_api",
    credentialFields: [
      {
        key: "shopify_store_domain",
        label: "Shopify Store Domain",
        type: "text",
        placeholder: "yourstore.myshopify.com",
        help: "Your Shopify store domain (without https://)",
      },
      {
        key: "shopify_admin_token",
        label: "Admin API Access Token",
        type: "password",
        placeholder: "shpat_...",
        help: "Shopify Admin → Settings → Apps → Develop apps → Create app → Admin API access token",
      },
    ],
    supportsRealMCP: false,
    restApiHint: "Shopify Admin GraphQL API: https://{shopify_store_domain}/admin/api/2025-07/graphql.json\nHeader: X-Shopify-Access-Token: {shopify_admin_token}",
  },

  wordpress: {
    slug: "wordpress",
    name: "WordPress",
    category: "content",
    icon: "📰",
    description: "Create and manage WordPress posts, pages, and media via the REST API",
    mcpServerUrl: null,
    authType: "rest_api",
    credentialFields: [
      {
        key: "wordpress_site_url",
        label: "WordPress Site URL",
        type: "url",
        placeholder: "https://yoursite.com",
        help: "The root URL of your WordPress site",
      },
      {
        key: "wordpress_app_password",
        label: "Application Password",
        type: "password",
        placeholder: "xxxx xxxx xxxx xxxx xxxx xxxx",
        help: "WordPress Admin → Users → Profile → Application Passwords → Generate",
      },
    ],
    supportsRealMCP: false,
    restApiHint: "WordPress REST API: {wordpress_site_url}/wp-json/wp/v2\nAuth: Basic base64(username:{wordpress_app_password})\nPOST /posts to create, GET /posts to list",
  },

  framer: {
    slug: "framer",
    name: "Framer",
    category: "design",
    icon: "🖼️",
    description: "Import animated components and layouts via the Framer API",
    mcpServerUrl: null,
    authType: "rest_api",
    credentialFields: [
      {
        key: "framer_api_token",
        label: "Framer API Token",
        type: "password",
        placeholder: "...",
        help: "Create at framer.com/developers → API Tokens",
      },
    ],
    supportsRealMCP: false,
    restApiHint: "Framer REST API: https://api.framer.com/store/v1\nHeader: Authorization: Bearer {framer_api_token}",
  },

  mailchimp: {
    slug: "mailchimp",
    name: "Mailchimp",
    category: "communication",
    icon: "🐵",
    description: "Manage audiences, campaigns, and subscribers via the Mailchimp API",
    mcpServerUrl: null,
    authType: "api_key",
    credentialFields: [
      {
        key: "api_key",
        label: "Mailchimp API Key",
        type: "password",
        placeholder: "xxxxxxxxxxxxxxxx-us1",
        help: "Find at mailchimp.com/account → Extras → API keys",
      },
    ],
    supportsRealMCP: false,
    restApiHint: "Mailchimp REST API: https://{dc}.api.mailchimp.com/3.0 (dc = last part of API key)\nAuth: Basic base64(anystring:{api_key})",
  },

  resend: {
    slug: "resend",
    name: "Resend",
    category: "communication",
    icon: "📨",
    description: "Transactional email sending via the Resend API",
    mcpServerUrl: null,
    authType: "api_key",
    credentialFields: [
      {
        key: "api_key",
        label: "Resend API Key",
        type: "password",
        placeholder: "re_...",
        help: "Create an API key at resend.com/api-keys",
      },
    ],
    supportsRealMCP: false,
    restApiHint: "Resend API: POST https://api.resend.com/emails\nHeader: Authorization: Bearer {api_key}\nBody: { from, to, subject, html }",
  },

  twilio: {
    slug: "twilio",
    name: "Twilio",
    category: "communication",
    icon: "📱",
    description: "Send SMS, WhatsApp messages, and make calls via the Twilio API",
    mcpServerUrl: null,
    authType: "api_key",
    credentialFields: [
      {
        key: "account_sid",
        label: "Account SID",
        type: "text",
        placeholder: "ACxxxxxxxxxxxxxxxx",
        help: "Found on your Twilio Console dashboard",
      },
      {
        key: "auth_token",
        label: "Auth Token",
        type: "password",
        placeholder: "...",
        help: "Found on your Twilio Console dashboard",
      },
      {
        key: "phone_number",
        label: "Twilio Phone Number",
        type: "text",
        placeholder: "+15551234567",
        help: "Your Twilio phone number in E.164 format (optional)",
        optional: true,
      },
    ],
    supportsRealMCP: false,
    restApiHint: "Twilio API: POST https://api.twilio.com/2010-04-01/Accounts/{account_sid}/Messages.json\nAuth: Basic base64({account_sid}:{auth_token})",
  },

  sendgrid: {
    slug: "sendgrid",
    name: "SendGrid",
    category: "communication",
    icon: "📧",
    description: "Send transactional and marketing email via the SendGrid API",
    mcpServerUrl: null,
    authType: "api_key",
    credentialFields: [
      {
        key: "api_key",
        label: "SendGrid API Key",
        type: "password",
        placeholder: "SG...",
        help: "Create at app.sendgrid.com/settings/api_keys",
      },
    ],
    supportsRealMCP: false,
    restApiHint: "SendGrid API: POST https://api.sendgrid.com/v3/mail/send\nHeader: Authorization: Bearer {api_key}",
  },

  mongodb: {
    slug: "mongodb",
    name: "MongoDB Atlas",
    category: "database",
    icon: "🍃",
    description: "MongoDB Atlas database for generated apps — connect via connection string",
    mcpServerUrl: null,
    authType: "api_key",
    credentialFields: [
      {
        key: "connection_string",
        label: "MongoDB Atlas Connection String",
        type: "password",
        placeholder: "mongodb+srv://user:pass@cluster.mongodb.net/dbname",
        help: "Get from cloud.mongodb.com → Database → Connect → Drivers",
      },
    ],
    supportsRealMCP: false,
    restApiHint: "MongoDB Atlas: use MONGODB_URI={connection_string} with Mongoose in the Node backend",
  },

  railway: {
    slug: "railway",
    name: "Railway",
    category: "devtools",
    icon: "🚂",
    description: "Deploy to Railway from generated apps",
    mcpServerUrl: null,
    authType: "bearer_token",
    credentialFields: [
      {
        key: "api_token",
        label: "Railway API Token",
        type: "password",
        placeholder: "...",
        help: "Create at railway.app/account/tokens",
      },
    ],
    supportsRealMCP: false,
    restApiHint: "Railway GraphQL API: POST https://backboard.railway.app/graphql/v2\nHeader: Authorization: Bearer {api_token}",
  },
};

// ── Internal platform-level tools (not user-facing) ──────────────────────────
// These load from env vars automatically; users don't need to connect them.

export const INTERNAL_MCP_PROVIDERS: Record<string, McpProvider> = {
  firecrawl: {
    slug: "firecrawl",
    name: "Firecrawl",
    category: "devtools",
    icon: "🔥",
    description: "Scrape and crawl any URL, extract structured data, search the web",
    mcpServerUrl: "https://mcp.firecrawl.dev",
    authType: "bearer_token",
    credentialFields: [{ key: "firecrawl_api_key", label: "Firecrawl API Key", type: "password", placeholder: "fc-..." }],
    supportsRealMCP: true,
    internal: true,
  },

  exa: {
    slug: "exa",
    name: "Exa",
    category: "devtools",
    icon: "🔍",
    description: "Semantic web search and content retrieval optimised for AI agents",
    mcpServerUrl: "https://mcp.exa.ai/mcp",
    authType: "bearer_token",
    credentialFields: [{ key: "exa_api_key", label: "Exa API Key", type: "password", placeholder: "..." }],
    supportsRealMCP: true,
    internal: true,
  },
};

export function getMcpProvider(slug: string): McpProvider | undefined {
  return MCP_REGISTRY[slug] ?? INTERNAL_MCP_PROVIDERS[slug];
}

export function resolveServerUrl(
  provider: McpProvider,
  creds: Record<string, string>,
): string | null {
  if (provider.mcpServerUrl === null) return null;
  if (typeof provider.mcpServerUrl === "function") {
    const url = provider.mcpServerUrl(creds);
    return url || null;
  }
  return provider.mcpServerUrl;
}
