import { Template } from 'e2b'

// ── Lampcode preview sandbox — Next.js template ───────────────────────────────
// Bakes Next.js + App Router baseline into the image, pre-installs deps.
// Dev server: `next dev --port 3000 --hostname 0.0.0.0`
// The backend starts this command; NO CMD is set here to avoid race conditions.

const PKG_JSON = `{
  "name": "lampcode-nextjs-app",
  "private": true,
  "scripts": {
    "dev": "next dev --port 3000 --hostname 0.0.0.0",
    "build": "next build",
    "start": "next start --port 3000 --hostname 0.0.0.0"
  },
  "dependencies": {
    "next": "14.2.10",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "@supabase/supabase-js": "2.45.0",
    "@supabase/ssr": "0.5.1",
    "mongoose": "8.7.0",
    "jsonwebtoken": "9.0.2",
    "bcryptjs": "2.4.3",
    "zod": "3.23.8"
  },
  "devDependencies": {
    "typescript": "5.5.4",
    "@types/react": "18.3.5",
    "@types/react-dom": "18.3.0",
    "@types/node": "22.5.4",
    "@types/jsonwebtoken": "9.0.6",
    "@types/bcryptjs": "2.4.6"
  }
}`

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {}
module.exports = nextConfig`

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`

const LAYOUT_TSX = `import type { Metadata } from 'next'
import './globals.css'
export const metadata: Metadata = { title: 'App', description: 'Generated by Lampcode' }
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body>{children}</body></html>
}`

const PAGE_TSX = `export default function Page() {
  return <main style={{ padding: 24, fontFamily: 'system-ui' }}>Loading…</main>
}`

const GLOBALS_CSS = `* { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, -apple-system, sans-serif; }`

const writeFile = (path: string, body: string): string => {
  const b64 = Buffer.from(body, 'utf8').toString('base64')
  return `RUN mkdir -p "$(dirname ${path})" && echo '${b64}' | base64 -d > ${path}`
}

const dockerfile = [
  'FROM node:20-slim',
  'RUN apt-get update && apt-get install -y git curl ca-certificates && rm -rf /var/lib/apt/lists/*',
  'RUN npm install -g typescript',
  'WORKDIR /home/user/app',
  // Disable Next.js telemetry + Google Fonts network calls during build/dev.
  // Without this, Next.js tries to phone home during `next build` and `next dev`
  // inside the E2B build environment where those calls never resolve, causing
  // the build to hang for exactly 1 hour (the E2B default build timeout).
  'ENV NEXT_TELEMETRY_DISABLED=1',
  writeFile('/home/user/app/package.json', PKG_JSON),
  writeFile('/home/user/app/next.config.js', NEXT_CONFIG),
  writeFile('/home/user/app/tsconfig.json', TSCONFIG),
  writeFile('/home/user/app/app/layout.tsx', LAYOUT_TSX),
  writeFile('/home/user/app/app/page.tsx', PAGE_TSX),
  writeFile('/home/user/app/app/globals.css', GLOBALS_CSS),
  'RUN npm install',
  // Warm next dev cache: start server, wait for boot, hit / to trigger route
  // compilation, then SIGKILL all next/node children immediately.
  // `wait $PID` was hanging for 30-60 seconds (Next.js graceful shutdown),
  // causing E2B builder to terminate the entire RUN step at its 60s timeout.
  // Fix: use kill -9 (SIGKILL) — no cleanup needed, no waiting.
  'RUN npx next dev --port 3000 --hostname 0.0.0.0 & PID=$!; sleep 10; curl -sf --max-time 30 http://localhost:3000/ > /dev/null || true; sleep 5; kill -9 $PID 2>/dev/null || true; pkill -9 -f "next" 2>/dev/null || true; sleep 2',
].join('\n')

export const template = Template().fromDockerfile(dockerfile)
