import { Template } from 'e2b'

// ── Lampcode preview sandbox — Next.js template ───────────────────────────────
// Architecture:
//   setStartCmd  → E2B runs `npm run dev` when the sandbox boots.
//   setReadyCmd  → E2B waits for this to exit 0, then snapshots the running
//                  sandbox (with .next/ already compiled). Every resume starts
//                  from that warm snapshot — no cold-compile on user request.
//
// Previously we used a RUN-step warm-cache hack (start dev, curl, kill -9).
// That caused "signal: killed" build failures because pkill -f "next" matched
// the Docker builder shell itself (its cmdline contained "next").
// The setStartCmd/setReadyCmd approach is the correct E2B-native pattern.

const PKG_JSON = `{
  "name": "lampcode-nextjs-app",
  "private": true,
  "scripts": {
    "dev": "next dev --port 3000 --hostname 0.0.0.0",
    "build": "next build",
    "start": "next start --port 3000 --hostname 0.0.0.0"
  },
  "dependencies": {
    "next": "14.2.10",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "@supabase/supabase-js": "2.45.0",
    "@supabase/ssr": "0.5.1",
    "mongoose": "8.7.0",
    "jsonwebtoken": "9.0.2",
    "bcryptjs": "2.4.3",
    "zod": "3.23.8"
  },
  "devDependencies": {
    "typescript": "5.5.4",
    "@types/react": "18.3.5",
    "@types/react-dom": "18.3.0",
    "@types/node": "22.5.4",
    "@types/jsonwebtoken": "9.0.6",
    "@types/bcryptjs": "2.4.6"
  }
}`

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {}
module.exports = nextConfig`

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`

const LAYOUT_TSX = `import type { Metadata } from 'next'
import './globals.css'
export const metadata: Metadata = { title: 'App', description: 'Generated by Lampcode' }
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body>{children}</body></html>
}`

const PAGE_TSX = `export default function Page() {
  return <main style={{ padding: 24, fontFamily: 'system-ui' }}>Loading…</main>
}`

const GLOBALS_CSS = `* { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, -apple-system, sans-serif; }`

const writeFile = (path: string, body: string): string => {
  const b64 = Buffer.from(body, 'utf8').toString('base64')
  return `RUN mkdir -p "$(dirname ${path})" && echo '${b64}' | base64 -d > ${path}`
}

const dockerfile = [
  'FROM node:20-slim',
  // Disable Next.js telemetry + Google Fonts network calls during build/dev.
  // Without this, Next.js tries to phone home and hangs in E2B's build env.
  'ENV NEXT_TELEMETRY_DISABLED=1',
  'RUN apt-get update && apt-get install -y git curl ca-certificates && rm -rf /var/lib/apt/lists/*',
  'RUN npm install -g typescript',
  'WORKDIR /home/user/app',
  writeFile('/home/user/app/package.json', PKG_JSON),
  writeFile('/home/user/app/next.config.js', NEXT_CONFIG),
  writeFile('/home/user/app/tsconfig.json', TSCONFIG),
  writeFile('/home/user/app/app/layout.tsx', LAYOUT_TSX),
  writeFile('/home/user/app/app/page.tsx', PAGE_TSX),
  writeFile('/home/user/app/app/globals.css', GLOBALS_CSS),
  'RUN npm install',
].join('\n')

export const template = Template()
  .fromDockerfile(dockerfile)
  // E2B runs this when the sandbox starts. Foreground process — no & or PID tricks.
  .setStartCmd('npm run dev')
  // E2B polls this until exit 0, then snapshots the running sandbox.
  // The curl hits / which triggers Next.js route compilation before snapshot.
  .setReadyCmd('until curl -sf http://localhost:3000/ > /dev/null; do sleep 1; done')
